'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const auth=url&&key?createClient(url,key):null;
export default function Dashboard(){
  const [email,setEmail]=useState(''),[otp,setOtp]=useState(''),[session,setSession]=useState<string|null>(null),[data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[pair,setPair]=useState('');
  async function request(path:string,payload?:unknown,token=session){const response=await fetch('/api/'+path,{method:payload===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:payload===undefined?undefined:JSON.stringify(payload)});const value=await response.json();if(!response.ok)throw new Error(value.error);return value;}
  useEffect(()=>{if(!auth)return;auth.auth.getSession().then(({data})=>setSession(data.session?.access_token??null));const {data:listener}=auth.auth.onAuthStateChange((_,s)=>setSession(s?.access_token??null));return()=>listener.subscription.unsubscribe();},[]);
  useEffect(()=>{if(!session)return;const refresh=()=>request('dashboard').then(setData).catch(e=>setError(e.message));refresh();const timer=setInterval(refresh,30000);return()=>clearInterval(timer);},[session]);
  async function sendCode(){if(!auth)return;const {error}=await auth.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error)setError(error.message);else setMessage('Check your email for the sign-in code.');}
  async function signIn(){if(!auth)return;const {error}=await auth.auth.verifyOtp({email,token:otp,type:'email'});if(error)setError(error.message);}
  async function save(profile:any){try{const r=await request('dashboard',profile);setData({...data,profile:r.profile});}catch(e:any){setError(e.message);}}
  async function pairWorker(){try{const r=await request('pair',{});setPair(r.token);}catch(e:any){setError(e.message);}}
  if(!auth)return <main><h1>ClipRank control plane</h1><p>Configure Supabase environment variables and apply the included database migration before deploying.</p></main>;
  if(!session)return <main><h1>ClipRank</h1><p>Sign in to your content studio. Your computer does the production work.</p><section><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button onClick={sendCode}>Send sign-in code</button><label>Code<input value={otp} onChange={e=>setOtp(e.target.value)}/></label><button onClick={signIn}>Sign in</button><p>{message}</p><p className="error">{error}</p></section></main>;
  if(!data)return <main>{error||'Loading your studio…'}</main>;
  const machine=data.workers?.find((w:any)=>!w.revoked),online=machine?.last_seen&&Date.now()-Date.parse(machine.last_seen)<90000;
  return <main><h1>ClipRank Autopilot</h1><p>{data.profile.name} · Surprising, intense and funny visual moments.</p><p className="error">{error}</p><div className="grid"><span className="pill">{data.profile.enabled?'Enabled':'Paused'}</span><span className="pill">Worker {online?'Online':'Offline'}</span><span className="pill">3 candidates · Up to {data.profile.publication_limit} published / day</span></div>
    <section><h2>Channel</h2><label>Channel name<input value={data.profile.name} onChange={e=>setData({...data,profile:{...data.profile,name:e.target.value}})}/></label><label>Timezone<input value={data.profile.timezone} onChange={e=>setData({...data,profile:{...data.profile,timezone:e.target.value}})}/></label><label><input type="checkbox" checked={data.profile.auto_publish} onChange={e=>setData({...data,profile:{...data.profile,auto_publish:e.target.checked}})}/>Automatically publish only approved videos</label><label>Visibility<select value={data.profile.privacy} onChange={e=>setData({...data,profile:{...data.profile,privacy:e.target.value}})}><option>private</option><option>unlisted</option><option>public</option></select></label><button onClick={()=>save(data.profile)}>Save</button><button onClick={()=>save({...data.profile,enabled:!data.profile.enabled})}>{data.profile.enabled?'Pause Autopilot':'Enable Autopilot'}</button></section>
    <section><h2>Worker pairing</h2><p>Connect the worker from your computer once. YouTube credentials and AI keys stay on the computer. Pairing replaces the previous worker token.</p><button onClick={pairWorker}>Create pairing token</button>{pair&&<><p>Copy this token into the worker's pairing prompt. It is shown only here.</p><code>{pair}</code></>}</section>
    <section><h2>Today</h2>{machine?.summary?.tasks?.length?machine.summary.tasks.map((task:any)=><article key={task.id}><b>{task.title}</b><p>{task.status}</p>{task.video_id&&<a href={'https://www.youtube.com/watch?v='+task.video_id} target="_blank" rel="noreferrer">Open on YouTube</a>}</article>):<p>Waiting for the paired worker. Offline jobs remain queued. Local previews are available in the local studio.</p>}</section><p>Vercel Hobby is restricted to personal non-commercial use. Use an eligible hosting plan for a monetized studio. No income or view guarantees.</p><button onClick={()=>auth.auth.signOut()}>Sign out</button>
  </main>;
}
