"""Original background music, so a Short never needs borrowed audio.

`sad_bed` returns a music bed for a given length: a track from the user's licensed library when one is tagged
'emotional' (their rights evidence is on file), otherwise an original synthesized ambient piece (slow A-minor
progression Am - F - C - G, soft pad, sparse bell-like melody, reverb). Generated music belongs to ClipRank's own output,
so there is nothing to claim or clear. The ffmpeg command is built from constants here; nothing comes from a model.
"""
import hashlib
from pathlib import Path
from typing import Any, Dict, Tuple

from app.core.runtime import run_process

BAR = 8.0                      # seconds per chord (slow, 30 bpm feel)
SAMPLE_RATE = 48000
PROGRESSION = [                # Am - F - C - G, low pad voicings (Hz)
    [110.00, 164.81, 220.00, 261.63],
    [87.31, 130.81, 174.61, 220.00],
    [130.81, 196.00, 261.63, 329.63],
    [98.00, 146.83, 196.00, 246.94],
]
MELODY = [                     # (bar, seconds into the bar, Hz): sparse, rising and falling
    (0, 1.0, 659.25), (0, 4.5, 523.25), (1, 1.0, 698.46), (1, 4.5, 523.25),
    (2, 1.0, 784.00), (2, 4.5, 659.25), (3, 1.0, 587.33), (3, 4.5, 493.88),
]
LOOP_SECONDS = BAR * len(PROGRESSION)


def build_loop_command(output: Path) -> list:
    inputs, filters, bars = [], [], []
    for bar, voicing in enumerate(PROGRESSION):
        pad = []
        for freq in voicing:
            inputs += ["-f", "lavfi", "-i", f"sine=frequency={freq}:sample_rate={SAMPLE_RATE}:duration={BAR}"]
            pad.append(f"[{len(inputs) // 4 - 1}:a]")
        filters.append("".join(pad) + f"amix=inputs={len(voicing)}:normalize=0,volume=0.30,afade=t=in:d=2.5,afade=t=out:st={BAR - 3}:d=3[pad{bar}]")
        parts = [f"[pad{bar}]"]
        for b, at, freq in [m for m in MELODY if m[0] == bar]:
            inputs += ["-f", "lavfi", "-i", f"sine=frequency={freq}:sample_rate={SAMPLE_RATE}:duration=3.2"]
            index = len(inputs) // 4 - 1
            filters.append(f"[{index}:a]volume=0.20,afade=t=in:d=0.03,afade=t=out:st=0.15:d=3,adelay={int(at * 1000)}:all=1,apad=whole_dur={BAR}[note{index}]")
            parts.append(f"[note{index}]")
        filters.append("".join(parts) + f"amix=inputs={len(parts)}:normalize=0,atrim=duration={BAR}[bar{bar}]")
        bars.append(f"[bar{bar}]")
    filters.append("".join(bars) + f"concat=n={len(bars)}:v=0:a=1,tremolo=f=0.2:d=0.25,lowpass=f=2400,"
                   "aecho=0.8:0.85:70|1300:0.45|0.28,aformat=channel_layouts=stereo,loudnorm=I=-20:TP=-3:LRA=7[out]")
    return ["ffmpeg", "-v", "error", "-y", *inputs, "-filter_complex", ";".join(filters), "-map", "[out]",
            "-ar", str(SAMPLE_RATE), "-ac", "2", "-c:a", "pcm_s16le", str(output)]


def generate_loop(folder: Path) -> Path:
    """One 32-second loop, cached by content so it is built once."""
    folder.mkdir(parents=True, exist_ok=True)
    loop = folder / f"sad_loop_{hashlib.sha1(repr((PROGRESSION, MELODY, BAR)).encode()).hexdigest()[:8]}.wav"
    if not loop.is_file() or loop.stat().st_size < 100_000:
        run_process(build_loop_command(loop), timeout=180)
    return loop


def fit_to_length(loop: Path, output: Path, seconds: float) -> Path:
    """Loop the bed to the video's length with a gentle fade in and a longer fade out."""
    output.parent.mkdir(parents=True, exist_ok=True)
    fade_out = min(3.0, max(.5, seconds / 4))
    run_process(["ffmpeg", "-v", "error", "-y", "-stream_loop", "-1", "-i", str(loop), "-t", f"{seconds:.3f}",
                 "-af", f"afade=t=in:d=1.5,afade=t=out:st={max(0.0, seconds - fade_out):.3f}:d={fade_out:.3f}",
                 "-ar", str(SAMPLE_RATE), "-ac", "2", "-c:a", "pcm_s16le", str(output)])
    return output


def sad_bed(folder: Path, seconds: float, mood: str = "emotional") -> Tuple[Path, Dict[str, Any]]:
    """(wav, provenance). A tagged track from the user's licensed library wins; otherwise original generated music."""
    folder = Path(folder)
    try:
        from app.pipelines.movie.music import CinematicMusicDirector
        track = CinematicMusicDirector.select(mood)
        if track:
            path, info = CinematicMusicDirector.prepare(track, folder, 0.0, seconds)
            return path, {**info, "source": "licensed library", "generated": False}
    except Exception:       # a broken library entry must never stop a Short: fall back to original music
        pass
    path = fit_to_length(generate_loop(folder.parent / "music_cache"), folder / "sad_bed.wav", seconds)
    return path, {"track_name": "ClipRank original ambient (A minor)", "source": "generated by ClipRank", "generated": True,
                  "license": "original", "creator": "ClipRank", "rights_status": "commercial_use_permitted",
                  "source_type": "cliprank_generated", "usage_rights": "Original synthesized audio; no third-party material"}
