import React,{useEffect,useState} from 'react';
import {Bot,Pause,Play,RefreshCw,ArrowRight} from 'lucide-react';
import {studioRequest} from '../api';

export function AutopilotPage({onOpenProject,onSettings}:{onOpenProject:(project:string,job:string)=>void;onSettings:()=>void}) {
  const [data,setData]=useState<any>(null);const [profile,setProfile]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  async function refresh(){try{const r=await studioRequest('/dashboard');setData(r);setProfile((p:any)=>p||r.profile);}catch(e:any){setError(e.message);}}
  useEffect(()=>{refresh();const t=setInterval(refresh,10000);return()=>clearInterval(t);},[]);
  async function save(next:any){setBusy(true);setError('');try{setProfile(await studioRequest('/profile',next));await refresh();setMessage('Autopilot settings saved.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function plan(){setBusy(true);setError('');try{const r=await studioRequest('/plan',{});setMessage(`${r.candidates.length} candidates queued. Publishing still requires every quality gate.`);await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  if(!data||!profile)return <div className="p-8">{error||'Loading studio…'}</div>;
  const voiceReady=profile.tts_engine==='edge'||(profile.tts_engine==='pocket'?data.pocket_voice?.ready:data.local_voice.ready);
  const ready=voiceReady&&data.worker.online&&(!profile.auto_publish||data.youtube.connected);
  return <div className="flex-1 overflow-y-auto p-8"><div className="max-w-4xl mx-auto space-y-6 pb-16">
    <header className="flex justify-between gap-4 items-center"><div><h1 className="font-bold text-2xl flex items-center gap-2"><Bot/>ClipRank Autopilot</h1><p className="text-zinc-500 text-sm mt-1">{profile.name} · Visual payoff first.</p></div><span className={`text-sm rounded-full px-3 py-1 ${profile.enabled?'bg-emerald-100 text-emerald-900':'bg-zinc-200'}`}>{profile.enabled?'Running':'Paused'}</span></header>
    {error&&<p role="alert" className="bg-red-50 text-red-800 rounded-xl p-4">{error}</p>}{message&&<p role="status" className="text-sm text-cyan-800">{message}</p>}
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Production target','3 candidates / day'],['Publishing',`Up to ${profile.publication_limit} / day`],['Worker',data.worker.online?'Online':'Offline'],['YouTube',data.youtube.connected?data.youtube.channel_title:'Not connected']].map(([label,value])=><div key={label} className="bg-white border rounded-2xl p-4"><p className="text-xs text-zinc-500">{label}</p><p className="text-sm font-semibold mt-2">{value}</p></div>)}</div>
    <p className="text-xs text-zinc-500">Worker load: {data.worker.cpu_load??'—'} · Peak RAM: {data.worker.process_peak_ram_mb??'—'} MB · Free disk: {data.worker.disk_free_gb??'—'} GB</p>
    <div className="bg-white border rounded-2xl p-6 space-y-5"><h2 className="font-semibold">Channel setup</h2><p className="text-sm text-zinc-600">{profile.positioning}</p><div className="flex flex-wrap gap-2">{profile.pillars.map((pillar:string)=><span key={pillar} className="text-xs bg-cyan-50 text-cyan-900 rounded-full px-3 py-1">{pillar.replaceAll('_',' ')}</span>)}</div><div className="grid md:grid-cols-2 gap-4">
      <label className="text-sm">Channel name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>
      <label className="text-sm">Timezone<input value={profile.timezone} onChange={e=>setProfile({...profile,timezone:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>
      <label className="text-sm">AI mode<select value={profile.ai_mode} onChange={e=>setProfile({...profile,ai_mode:e.target.value})} className="w-full border rounded-xl p-2 mt-1"><option value="auto">Automatic · local first</option><option value="local">Local only</option><option value="gemini">Google AI Studio</option></select></label>
      <label className="text-sm">Narration<select value={profile.tts_engine} onChange={e=>setProfile({...profile,tts_engine:e.target.value})} className="w-full border rounded-xl p-2 mt-1"><option value="pocket">Local Pocket TTS</option><option value="kokoro">Local Kokoro</option><option value="edge">Online neural voice</option></select></label>
      <label className="text-sm">Voice style<select value={profile.voice_profile} onChange={e=>setProfile({...profile,voice_profile:e.target.value})} className="w-full border rounded-xl p-2 mt-1">{['Curious','Energetic','Documentary','Fast Explainer'].map(x=><option key={x}>{x}</option>)}</select></label>
      <label className="text-sm">Publishing limit<select value={profile.publication_limit} onChange={e=>setProfile({...profile,publication_limit:Number(e.target.value)})} className="w-full border rounded-xl p-2 mt-1"><option value={0}>0 · Produce only</option><option value={1}>Up to 1 per day</option><option value={2}>Up to 2 per day</option><option value={3}>2 + exceptional third</option></select></label>
      <label className="text-sm">Reuse rights<select value={profile.rights_policy} onChange={e=>setProfile({...profile,rights_policy:e.target.value})} className="w-full border rounded-xl p-2 mt-1"><option value="user_managed">I manage source rights</option><option value="documented_permission">Documented permission only</option></select></label>
      <label className="text-sm">Visibility<select value={profile.privacy} onChange={e=>setProfile({...profile,privacy:e.target.value})} className="w-full border rounded-xl p-2 mt-1"><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public</option></select></label>
      <label className="text-sm">Local publishing hours<input value={profile.publishing_hours.join(', ')} onChange={e=>setProfile({...profile,publishing_hours:e.target.value.split(',').map((x:string)=>Number(x.trim()))})} className="w-full border rounded-xl p-2 mt-1"/></label>
    </div><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={profile.auto_publish} onChange={e=>setProfile({...profile,auto_publish:e.target.checked})}/>Automatically stage approved Shorts privately, then publish after copyright clearance</label>
      {profile.tts_engine==='pocket'&&<p className={`text-sm ${voiceReady?'text-emerald-700':'text-amber-800'}`}>{data.pocket_voice?.message||'Checking Pocket TTS…'}</p>}
      {!voiceReady&&profile.tts_engine==='kokoro'&&<p className="text-sm text-amber-800">Local voice needs an installed Kokoro model and runtime. Connect it later, or select another narration engine.</p>}
      {!data.youtube.connected&&<button onClick={onSettings} className="text-sm text-cyan-800 underline">Connect YouTube in Settings</button>}
      <div className="flex flex-wrap gap-3"><button disabled={busy} onClick={()=>save(profile)} className="border rounded-xl px-4 py-2 text-sm">Save settings</button><button disabled={busy||(!profile.enabled&&!ready)} onClick={()=>save({...profile,enabled:!profile.enabled})} className="bg-zinc-900 text-white rounded-xl px-4 py-2 text-sm disabled:opacity-40">{profile.enabled?<Pause className="inline w-4 h-4 mr-2"/>:<Play className="inline w-4 h-4 mr-2"/>}{profile.enabled?'Pause Autopilot':'Enable Autopilot'}</button><button disabled={busy||!voiceReady} onClick={plan} className="border rounded-xl px-4 py-2 text-sm disabled:opacity-40"><RefreshCw className="inline w-4 h-4 mr-2"/>Plan today</button></div>
    </div>
    <p className="text-sm text-zinc-600">Discover up to 30 opportunities → deeply analyze 10 → select up to 5 finalists → produce up to 3 → publish the best 0–3. No quota fill. Copyright checks remain separate from video QC.</p><section className="space-y-3"><h2 className="font-semibold">Production queue</h2>{!data.tasks.length&&<p className="text-sm text-zinc-500">No candidates yet. Discover verified moments or plan today's productions.</p>}{data.tasks.slice(0,12).map((task:any)=><div key={task.id} className="bg-white border rounded-xl p-4 flex justify-between items-center gap-3"><div><p className="text-sm font-medium">{task.checkpoint.result?.metadata?.title||task.checkpoint.research?.title||'Visual entertainment Short'}</p><p className="text-xs text-zinc-500 mt-1">{task.stage.replaceAll('_',' ')}{task.publish_at&&` · ${new Date(task.publish_at).toLocaleString()}`}</p>{task.error&&<p className="text-xs text-red-700 mt-2">{task.error}</p>}</div><button onClick={()=>onOpenProject(task.project_id,task.id)} className="text-sm flex items-center gap-1">Inspect<ArrowRight className="w-4 h-4"/></button></div>)}</section>
    <section className="bg-white border rounded-2xl p-6"><h2 className="font-semibold">Performance</h2><div className="flex flex-wrap gap-8 text-sm mt-4"><p>Observed views: <b>{data.performance.observed_views??'Not available yet'}</b></p><p>Subscribers gained: <b>{data.performance.observed_subscribers_gained??'Not available yet'}</b></p><p>Published in 7 days: <b>{data.performance.published_last_7_days}</b></p></div><p className="text-xs text-zinc-500 mt-4">{data.performance.metrics_window} {data.intelligence.learning_status}. No income or view guarantees.</p></section>
  </div></div>;
}
